/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_DeckType */

#ifndef _Included_com_onejoker_onejoker_DeckType
#define _Included_com_onejoker_onejoker_DeckType
#ifdef __cplusplus
extern "C" {
#endif
#undef com_onejoker_onejoker_DeckType_NTYPES
#define com_onejoker_onejoker_DeckType_NTYPES 6L
/*
 * Class:     com_onejoker_onejoker_DeckType
 * Method:    nCards
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_DeckType_nCards
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
