/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_CardList */

#ifndef _Included_com_onejoker_onejoker_CardList
#define _Included_com_onejoker_onejoker_CardList
#ifdef __cplusplus
extern "C" {
#endif
#undef com_onejoker_onejoker_CardList_ERDONLY
#define com_onejoker_onejoker_CardList_ERDONLY -2L
#undef com_onejoker_onejoker_CardList_EFULL
#define com_onejoker_onejoker_CardList_EFULL -3L
#undef com_onejoker_onejoker_CardList_EDUPLICATE
#define com_onejoker_onejoker_CardList_EDUPLICATE -4L
#undef com_onejoker_onejoker_CardList_EBADINDEX
#define com_onejoker_onejoker_CardList_EBADINDEX -5L
/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nStructSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nStructSize
  (JNIEnv *, jclass);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nAppend
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nAppend
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nClear
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nClear
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nDelete
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nDelete
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nEquals
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_onejoker_onejoker_CardList_nEquals
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nExtend
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nExtend
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nFill
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nFill
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nGet
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nGet
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nHash
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nHash
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nIndex
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nIndex
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nInsert
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nInsert
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nNew
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_onejoker_onejoker_CardList_nNew
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nPop
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nPop
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nRemove
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nRemove
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nReverse
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nReverse
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nSet
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nSet
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nShuffle
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nShuffle
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nSize
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nSize
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nSort
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nSort
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_onejoker_onejoker_CardList
 * Method:    nTruncate
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_CardList_nTruncate
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
