/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_CardCombinations */

#ifndef _Included_com_onejoker_onejoker_CardCombinations
#define _Included_com_onejoker_onejoker_CardCombinations
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
