/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_DeckType */

#ifndef _Included_com_onejoker_onejoker_DeckType
#define _Included_com_onejoker_onejoker_DeckType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onejoker_onejoker_DeckType
 * Method:    nCards
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_DeckType_nCards
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_onejoker_onejoker_DeckType
 * Method:    nTypes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_onejoker_onejoker_DeckType_nTypes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
