# OneJoker library <http://lcrocker.github.io/OneJoker>
# Token Makefile that just calls the real build script
#

.PHONY: module
module:
	python3 ../../build.py python

.PHONY: tests
tests:
	python3 ../../build.py pytests

.PHONY: run
run:
	python3 ../../build.py runpytests

.PHONY: clean
clean:
	python3 ../../build.py cleanpython
