/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_Iterator */

#ifndef _Included_com_onejoker_onejoker_Iterator
#define _Included_com_onejoker_onejoker_Iterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onejoker_onejoker_Iterator
 * Method:    _new
 * Signature: (Lcom/onejoker/onejoker/Sequence;Lcom/onejoker/onejoker/Sequence;[I)V
 */
JNIEXPORT void JNICALL Java_com_onejoker_onejoker_Iterator__1new
  (JNIEnv *, jobject, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
