/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_CardContext */

#ifndef _Included_com_onejoker_onejoker_CardContext
#define _Included_com_onejoker_onejoker_CardContext
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
