/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onejoker_onejoker_Sequence */

#ifndef _Included_com_onejoker_onejoker_Sequence
#define _Included_com_onejoker_onejoker_Sequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onejoker_onejoker_Sequence
 * Method:    _new
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_onejoker_onejoker_Sequence__1new
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
