# Token Makefile that just calls the real build script
#

.PHONY: all
all:
	python3 ../build.py python

.PHONY: clean
clean:
	python3 ../build.py pyclean

.PHONY: test
test:
	python3 ../build.py pytests
